from datetime import datetime, timezone
import logging
from fastapi import APIRouter, HTTPException
from fastapi.responses import Response
from fpdf import FPDF
from app.database.mongodb import (
    cases_collection,
    evidence_collection,
    analysis_collection,
    text_tracker_collection,
    audit_collection
)
from app.services.evidence_service import calculate_file_hash

router = APIRouter(prefix="/reports", tags=["Reports"])
logger = logging.getLogger(__name__)

def clean_pdf_text(val) -> str:
    """Sanitizes text for FPDF core Helvetica/latin-1 rendering without crash."""
    if val is None:
        return ""
    text = str(val)
    replacements = {
        "\u2014": "--",
        "\u2013": "-",
        "\u2018": "'",
        "\u2019": "'",
        "\u201c": '"',
        "\u201d": '"',
        "\u2026": "...",
        "\u2022": "*",
        "›": ">",
        "‹": "<",
        "✓": "[OK]",
        "✔": "[OK]",
        "❌": "[FAIL]",
        "⚠️": "[!]",
        "\u00a0": " ",
    }
    for orig, rep in replacements.items():
        text = text.replace(orig, rep)
    # Fallback encoding to latin-1 to strictly prevent FPDFUnicodeEncodingException
    return text.encode("latin-1", "replace").decode("latin-1")

class ForensicPDF(FPDF):
    def header(self):
        self.set_font("helvetica", "B", 10)
        self.set_text_color(71, 85, 105)
        self.cell(0, 8, "OFFICIAL DIGITAL FORENSICS INVESTIGATION REPORT | CONFIDENTIAL", new_x="LMARGIN", new_y="NEXT", align="R")
        self.set_draw_color(37, 99, 235)
        self.set_line_width(0.5)
        self.line(10, 18, 200, 18)
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("helvetica", "I", 8)
        self.set_text_color(148, 163, 184)
        self.cell(0, 10, clean_pdf_text(f"Page {self.page_no()}/{{nb}} - Generated by AI Forensics Platform"), align="C")

def build_case_report_data(case_id: str) -> dict:
    case = cases_collection.find_one({"case_id": case_id}, {"_id": 0})
    if not case:
        raise HTTPException(status_code=404, detail="Case not found")

    evidence_list = list(evidence_collection.find({"case_id": case_id}, {"_id": 0}))

    evidence_details = []
    total_indicators = 0
    max_risk_level = "Low"
    highest_score = 0
    all_recommendations = set()

    for ev in evidence_list:
        ev_id = ev.get("evidence_id")
        analysis = analysis_collection.find_one({"evidence_id": ev_id}, {"_id": 0})
        tracker = text_tracker_collection.find_one({"evidence_id": ev_id}, {"_id": 0})

        # Calculate current hash integrity
        file_path = ev.get("file_path", "")
        stored_hash = ev.get("file_hash", "N/A")
        integrity_status = "Unchecked"
        if file_path:
            try:
                curr = calculate_file_hash(file_path)
                integrity_status = "MATCH (VERIFIED)" if curr.lower() == stored_hash.lower() else "TAMPERED / MISMATCH"
            except Exception:
                integrity_status = "FILE INACCESSIBLE"

        # Tally risk
        risk = analysis.get("risk_level", "Low") if analysis else "Low"
        score = analysis.get("risk_score", 0) if analysis else 0
        if score > highest_score:
            highest_score = score
        if risk == "Critical":
            max_risk_level = "Critical"
        elif risk == "High" and max_risk_level != "Critical":
            max_risk_level = "High"
        elif risk == "Medium" and max_risk_level not in ["Critical", "High"]:
            max_risk_level = "Medium"

        if analysis and analysis.get("recommendations"):
            for r in analysis.get("recommendations"):
                all_recommendations.add(r)

        ind_count = 0
        if tracker:
            ind_count += len(tracker.get("indicators", []))
            if tracker.get("recommendations"):
                for r in tracker.get("recommendations"):
                    all_recommendations.add(r)
        elif analysis:
            ind_count += len(analysis.get("suspicious_indicators", []))

        total_indicators += ind_count

        evidence_details.append({
            "evidence_id": ev_id,
            "file_name": ev.get("file_name") or ev.get("evidence_name"),
            "file_type": ev.get("file_type") or ev.get("evidence_type"),
            "stored_hash": stored_hash,
            "integrity_status": integrity_status,
            "risk_level": risk,
            "risk_score": score,
            "indicator_count": ind_count,
            "analysis": analysis,
            "tracker": tracker
        })

    # Recent Audit Logs
    audit_logs = list(
        audit_collection.find({"case_id": case_id}, {"_id": 0})
        .sort("created_at", -1)
        .limit(10)
    )

    return {
        "case": case,
        "evidence_list": evidence_details,
        "total_evidence": len(evidence_list),
        "total_indicators": total_indicators,
        "max_risk_level": max_risk_level,
        "highest_score": highest_score,
        "recommendations": list(all_recommendations) if all_recommendations else [
            "Maintain baseline evidence custody.",
            "Verify all digital signatures and store secondary SHA-256 archives."
        ],
        "audit_logs": audit_logs,
        "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    }

@router.post("/{case_id}/generate")
def generate_report_text(case_id: str):
    data = build_case_report_data(case_id)
    c = data["case"]

    lines = [
        "=" * 80,
        "        DIGITAL FORENSICS COMPREHENSIVE INVESTIGATION REPORT",
        "=" * 80,
        f"Generated At: {data['generated_at']}",
        f"Case Reference ID: {c.get('case_id')}",
        f"Case Title:        {c.get('title', 'N/A')}",
        f"Crime Category:    {c.get('crime_category', 'General Investigation')}",
        f"Status:            {c.get('status', 'Open')}",
        f"Investigator ID:   {c.get('created_by') or c.get('investigator', 'Forensics Unit')}",
        f"Overall Risk Tier: {data['max_risk_level'].upper()} (Peak Score: {data['highest_score']}/100)",
        "-" * 80,
        "1. EXECUTIVE SUMMARY & THREAT ASSESSMENT",
        "-" * 80,
        f"This forensic examination covers {data['total_evidence']} piece(s) of seized digital evidence.",
        f"A total of {data['total_indicators']} threat indicators/artifacts were flagged across static and heuristic scans.",
        f"Case risk is rated {data['max_risk_level'].upper()}.",
        "",
        "-" * 80,
        "2. EVIDENCE INVENTORY & CHAIN OF CUSTODY INTEGRITY",
        "-" * 80,
    ]

    for idx, ev in enumerate(data["evidence_list"]):
        lines.append(f"Item #{idx + 1}: {ev['file_name']} [{ev['file_type']}]")
        lines.append(f"  - Evidence ID:       {ev['evidence_id']}")
        lines.append(f"  - SHA-256 Checksum:  {ev['stored_hash']}")
        lines.append(f"  - Integrity State:   {ev['integrity_status']}")
        lines.append(f"  - Risk Assessment:   {ev['risk_level']} (Score: {ev['risk_score']}/100)")
        lines.append(f"  - Flagged Artifacts: {ev['indicator_count']}")

        if ev.get("tracker"):
            t = ev["tracker"]
            lines.append(f"  - Text Tracker:     {t.get('total_lines', 0)} lines analyzed.")
            lines.append(f"  - Findings Summary:  {t.get('ai_summary', 'Scanned without critical flags.')}")
            top_indicators = t.get("indicators", [])[:5]
            if top_indicators:
                lines.append("    Key Artifacts:")
                for item in top_indicators:
                    lines.append(f"      * [L{item.get('line_number', 0)}] {item.get('type')}: {item.get('value')} ({item.get('severity')}) - {item.get('reason')}")
        lines.append("")

    lines.extend([
        "-" * 80,
        "3. ACTIONABLE FORENSIC RECOMMENDATIONS",
        "-" * 80,
    ])
    for idx, rec in enumerate(data["recommendations"]):
        lines.append(f"[{idx + 1}] {rec}")

    lines.extend([
        "",
        "-" * 80,
        "4. AUDIT TRAIL LOGS (RECENT ACTIVITY)",
        "-" * 80,
    ])
    for log in data["audit_logs"]:
        lines.append(f"- [{log.get('timestamp') or log.get('created_at')}] {log.get('action')}: {log.get('description')}")

    lines.extend([
        "",
        "=" * 80,
        "                END OF OFFICIAL FORENSIC REPORT",
        "=" * 80,
    ])

    report_string = "\n".join(lines)
    return {
        "report_text": report_string,
        "metadata": {
            "case_id": case_id,
            "total_evidence": data["total_evidence"],
            "total_indicators": data["total_indicators"],
            "max_risk_level": data["max_risk_level"],
            "highest_score": data["highest_score"]
        }
    }

@router.get("/{case_id}/pdf")
def get_report_pdf(case_id: str):
    try:
        data = build_case_report_data(case_id)
        c = data["case"]

        pdf = ForensicPDF()
        pdf.alias_nb_pages()
        pdf.add_page()
        pdf.set_auto_page_break(auto=True, margin=15)

        # Title
        pdf.set_font("helvetica", "B", 18)
        pdf.set_text_color(15, 23, 42)
        pdf.cell(0, 10, "DIGITAL FORENSICS INVESTIGATION REPORT", new_x="LMARGIN", new_y="NEXT", align="C")
        pdf.set_font("helvetica", "I", 10)
        pdf.set_text_color(71, 85, 105)
        pdf.cell(0, 6, clean_pdf_text(f"Generated: {data['generated_at']} | Case ID: {case_id}"), new_x="LMARGIN", new_y="NEXT", align="C")
        pdf.ln(6)

        # Case Metadata Box
        pdf.set_fill_color(241, 245, 249)
        pdf.rect(10, pdf.get_y(), 190, 32, "F")
        pdf.set_font("helvetica", "B", 11)
        pdf.set_text_color(15, 23, 42)
        pdf.set_xy(14, pdf.get_y() + 3)
        pdf.cell(90, 7, clean_pdf_text(f"Case Title: {c.get('title', 'Unknown')[:35]}"))
        pdf.cell(90, 7, clean_pdf_text(f"Category: {c.get('crime_category', 'Forensics')}"), new_x="LMARGIN", new_y="NEXT")

        pdf.set_x(14)
        pdf.cell(90, 7, clean_pdf_text(f"Status: {c.get('status', 'Open')}"))
        pdf.cell(90, 7, clean_pdf_text(f"Investigator: {c.get('created_by') or 'Lead Examiner'}"), new_x="LMARGIN", new_y="NEXT")

        pdf.set_x(14)
        pdf.cell(90, 7, clean_pdf_text(f"Total Evidence Items: {data['total_evidence']}"))
        if data["max_risk_level"] in ["Critical", "High"]:
            pdf.set_text_color(220, 38, 38)
        else:
            pdf.set_text_color(15, 23, 42)
        pdf.cell(90, 7, clean_pdf_text(f"Overall Case Risk: {data['max_risk_level'].upper()} ({data['highest_score']}/100)"), new_x="LMARGIN", new_y="NEXT")
        pdf.ln(8)

        # Section 1: Executive Summary
        pdf.set_font("helvetica", "B", 13)
        pdf.set_text_color(30, 58, 138)
        pdf.set_x(10)
        pdf.cell(190, 8, "1. Executive Summary", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("helvetica", size=10)
        pdf.set_text_color(51, 65, 85)
        summary_text = (
            f"An investigation was executed on case '{c.get('title')}'. A total of {data['total_evidence']} "
            f"digital evidence artifact(s) were cataloged, cryptographically hashed using SHA-256, "
            f"and subjected to deep heuristic pattern matching and AI entity extraction. "
            f"The cumulative analysis identified {data['total_indicators']} threat/suspicious indicators, "
            f"resulting in an overall incident threat severity of {data['max_risk_level'].upper()}."
        )
        pdf.set_x(10)
        pdf.multi_cell(190, 5.5, clean_pdf_text(summary_text))
        pdf.ln(5)

        # Section 2: Evidence Inventory
        pdf.set_font("helvetica", "B", 13)
        pdf.set_text_color(30, 58, 138)
        pdf.set_x(10)
        pdf.cell(190, 8, "2. Evidence Inventory & Hash Integrity", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

        for idx, ev in enumerate(data["evidence_list"]):
            pdf.set_x(10)
            pdf.set_font("helvetica", "B", 10)
            pdf.set_text_color(15, 23, 42)
            pdf.cell(190, 6, clean_pdf_text(f"Artifact #{idx + 1}: {ev['file_name']} ({ev['file_type']})"), new_x="LMARGIN", new_y="NEXT")

            pdf.set_x(10)
            pdf.set_font("helvetica", size=9)
            pdf.set_text_color(71, 85, 105)
            pdf.cell(35, 5, "SHA-256 Hash:")
            pdf.set_font("courier", size=8)
            pdf.cell(155, 5, clean_pdf_text(ev["stored_hash"][:55]), new_x="LMARGIN", new_y="NEXT")

            pdf.set_x(10)
            pdf.set_font("helvetica", size=9)
            pdf.cell(35, 5, "Integrity Status:")
            pdf.set_font("helvetica", "B", 9)
            if "VERIFIED" in ev["integrity_status"] or "MATCH" in ev["integrity_status"]:
                pdf.set_text_color(22, 101, 52)
            else:
                pdf.set_text_color(185, 28, 28)
            pdf.cell(65, 5, clean_pdf_text(ev["integrity_status"]))

            pdf.set_text_color(71, 85, 105)
            pdf.cell(25, 5, "Risk Rating:")
            pdf.set_font("helvetica", "B", 9)
            pdf.cell(65, 5, clean_pdf_text(f"{ev['risk_level']} ({ev['risk_score']}/100)"), new_x="LMARGIN", new_y="NEXT")

            if ev.get("tracker") and ev["tracker"].get("ai_summary"):
                pdf.set_x(10)
                pdf.set_font("helvetica", "I", 8.5)
                pdf.set_text_color(51, 65, 85)
                pdf.multi_cell(190, 4.5, clean_pdf_text(f"Text Tracker Finding: {ev['tracker']['ai_summary']}"))

            pdf.ln(3)

        pdf.ln(4)

        # Section 3: Recommendations
        pdf.set_font("helvetica", "B", 13)
        pdf.set_text_color(30, 58, 138)
        pdf.set_x(10)
        pdf.cell(190, 8, "3. Forensic Recommendations", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("helvetica", size=9.5)
        pdf.set_text_color(51, 65, 85)
        for idx, rec in enumerate(data["recommendations"]):
            pdf.set_x(10)
            pdf.multi_cell(190, 5.5, clean_pdf_text(f"{idx + 1}. {rec}"))

        pdf.ln(5)

        # Section 4: Audit Trail
        pdf.set_font("helvetica", "B", 13)
        pdf.set_text_color(30, 58, 138)
        pdf.set_x(10)
        pdf.cell(190, 8, "4. Recent Chain of Custody Audit Logs", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("helvetica", size=8.5)
        pdf.set_text_color(71, 85, 105)

        for log in data["audit_logs"][:8]:
            ts = log.get("timestamp") or log.get("created_at") or ""
            act = log.get("action", "")
            desc = log.get("description", "")
            pdf.set_x(10)
            pdf.multi_cell(190, 5, clean_pdf_text(f"[{str(ts)[:19]}] {act} - {desc[:90]}"))

        pdf_bytes = bytes(pdf.output())

        return Response(
            content=pdf_bytes,
            media_type="application/pdf",
            headers={
                "Content-Disposition": f"attachment; filename=Forensic_Report_{case_id}.pdf",
                "Access-Control-Expose-Headers": "Content-Disposition"
            }
        )
    except HTTPException:
        raise
    except Exception as e:
        logger.exception("Failed to compile forensic report PDF")
        raise HTTPException(
            status_code=500,
            detail=f"Report PDF generation error: {str(e)}"
        )
